spring:
  datasource:
    url: jdbc:mysql://localhost:3306/osahaneat
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  privateKey: Y68oPXSNa/HHkVhcBLLcUnMfxoB1WsIROZtqAnBOuDQ=

upload:
  path: C:\Users\Hi\Desktop\uploads

redis:
  host: localhost
  port: 6380